language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"

branches:
  only:
    - master
    - travis

# based on gist at https://gist.github.com/dan-blanchard/7045057
before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ];
    then wget http://repo.continuum.io/miniconda/Miniconda-3.3.0-Linux-x86_64.sh -O miniconda.sh;
    else wget http://repo.continuum.io/miniconda/Miniconda3-3.3.0-Linux-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are
  # not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - git checkout git@github.com:njwilson23/karta.git

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib
  - pip install karta/
  - pip install .

script:
  python tests.py

